# Generated by Django 3.1.3 on 2021-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0003_remove_chatmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='room',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
